DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id UUID PRIMARY KEY NOT NULL,
    username VARCHAR NOT NULL UNIQUE,
    email VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    created TIMESTAMP NOT NULL,
    modified TIMESTAMP NOT NULL,
    active BOOLEAN DEFAULT false NOT NULL
);
