DROP TABLE IF EXISTS tokens;
CREATE TABLE tokens (
    body TEXT PRIMARY KEY NOT NULL UNIQUE,
    user_id UUID REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL UNIQUE,
    created TIMESTAMP NOT NULL
);
