DROP TABLE IF EXISTS posts;
CREATE TABLE posts (
    id UUID PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    title VARCHAR NOT NULL,
    content VARCHAR NOT NULL,
    modified TIMESTAMP NOT NULL
);
